# Generated by Django 4.2.7 on 2023-11-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo_timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timers',
            name='name',
            field=models.CharField(default='DEF', max_length=10),
        ),
    ]
