# Generated by Django 4.2.7 on 2023-12-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo_timer', '0002_timers_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_desc', models.CharField(max_length=200)),
                ('est_pomodoro', models.IntegerField()),
            ],
        ),
    ]
