# Generated by Django 4.2.7 on 2023-12-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo_timer', '0003_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
