# Generated by Django 4.2.7 on 2023-12-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo_timer', '0004_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='custom_id',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
